<?php
const TRADE_STATUS = array(
    'CREATED' => 'CREATED',
    'CHECKOUT_SUCCESS' => 'CHECKOUT_SUCCESS',
    'CHECKOUT_FAILED' => 'CHECKOUT_FAILED',
    'SUBSCRIPTION_WAIT_REMIND' => 'SUBSCRIPTION_WAIT_REMIND',
    'SUBSCRIPTION_WAIT_CHARGE' => 'SUBSCRIPTION_WAIT_CHARGE',
    'SUBSCRIPTION_CHARGE_SUCCESS' => 'SUBSCRIPTION_CHARGE_SUCCESS',
    'SUBSCRIPTION_CHARGE_FAILED' => 'SUBSCRIPTION_CHARGE_FAILED',
    'SUBSCRIPTION_CANCEL' => 'SUBSCRIPTION_CANCEL',
);
const EVENETS = array(
    'CHECKOUT_SUCCESS' => 'CHECKOUT_SUCCESS',
    'CHECKOUT_FAILED' => 'CHECKOUT_FAILED',
    'SUBSCRIPTION_CHARGE_SUCCESS' => 'SUBSCRIPTION_CHARGE_SUCCESS',
    'SUBSCRIPTION_CHARGE_FAILED' => 'SUBSCRIPTION_CHARGE_FAILED',
    'SUBSCRIPTION_CANCEL' => 'SUBSCRIPTION_CANCEL',
);
const ADVANCE_REMINDER_TIME = 86400 * 5;
