<?php
const TRADE_STATUS = array(
    'CREATED' => 'CREATED',
    'CHECKOUT_SUCCEED' => 'CHECKOUT_SUCCEED',
    'CHECKOUT_FAIL' => 'CHECKOUT_FAIL',
    'SUBSCRIPTION_WAIT_REMIND' => 'SUBSCRIPTION_WAIT_REMIND',
    'SUBSCRIPTION_WAIT_CHARGE' => 'SUBSCRIPTION_WAIT_CHARGE',
    'SUBSCRIPTION_CHARGE_SUCCEED' => 'SUBSCRIPTION_CHARGE_SUCCEED',
    'SUBSCRIPTION_CHARGE_FAIL' => 'SUBSCRIPTION_CHARGE_FAIL',
    'CLOSED' => 'CLOSED',
);
const QUEUE_STATUS = array(
    'PENDING' => 'PENDING',
    'SUCCEED' => 'SUCCEED',
    'FAIL' => 'FAIL',
);
const ADVANCE_REMINDER_TIME = 86400 * 5;
