@startuml
!theme mars
participant Orange #FFA500
participant China #FF0000
participant Paypal #003087
participant Alipay #1677FF
Orange -> China : Jump to Checkout Page\n<color:#999>Use product, plan, customer, return_url, cancel_url, notify_url</color>
China -> China : Create a trade with a new trade_no\n<color:#999>Bind tarde with return_url, cancel_url, notify_url</color>
China -> Paypal : Create Product\n<color:#999>Use name, desc, link</color>
Paypal -> China : Return product_id\n<color:#999>Bind trade with prodcut_id</color>
China -> Paypal : Create and Active Plan\n<color:#999>Use product_id, name, desc, interval_count, interval_unit, fixed_price_value, fixed_price_currency_code</color>
Paypal -> China : Return plan_id\n<color:#999>Bind trade with plan_id</color>
China -> China : Create Customer\n<color:#999>Use email, last_name, first_name</color>\n<color:#999>Bind trade with customer_id</color>
China -> Paypal : Create Subscription\n<color:#999>Use customer as subscriber, plan_id, Return_url, cancel_url</color>
Paypal -> China : Return subscription_id, subscriber_id(customer_id) and agreement link\n<color:#999>Bind trade with subscription_id, customer_id</color>\n<color:#999>Jump to agreement link</color>
alt User Argee the argeement
Paypal -> China : Jump to China Gateway\n<color:#999>Return subscription_id</color>\n<color:#999>Update status to SUBSCRIPTION_WAIT_REMIND use subscription_id</color>
China -> Orange : Jump to return_url\n<color:#999>Remind user that authorization is successful and wait</color>
else User Cancle the argeement
Paypal -> China : Jump to China Gateway\n<color:#999>Return subscription_id</color>\n<color:#999>Update status to SUBSCRIPTION_CANCEL use subscription_id</color>
China -> Orange : Jump to cancel_url\n<color:#999>Remind user that authorization is successful and wait</color>
end
group Remind Queue: Run regularly
China --> China : Find all SUBSCRIPTION_WAIT_REMIND trades\n<color:#999>Use plan_id which bind with trade to find plan</color>\n<color:#999>Use plan to check if trade is about to due</color>
alt trade is about to due
China --> China : Use customer_id which bind with trade to find customer\n<color:#999>Get customer email and send emai</color>
China --> Orange : Notify notify_url with trade_no/subscription_id/customer_id\n<color:#999>Find member with trade_no/subscription_id/customer_id, remind them</color>
China --> China : Update status to SUBSCRIPTION_WAIT_CHARGE
end
end
group Auto debit
group WebHook Events: Paypal automatically deducts money and notify
Paypal --> China : Notify auto debit result with subscription_id/trade_no\n<color:#999>Use subscription_id/trade_no to find notify_url</color>
China --> Orange : Notify auto debit result to notify_url with trade_no/subscription_id/customer_id\n<color:#999>Bind member with trade_no/subscription_id/customer_id</color>
end
group Auto Debit Queue: Alipay needs to initiate a debit request, Run regularly
China -> China : Find all SUBSCRIPTION_WAIT_CHARGE trades\n<color:#999>Use plan_id which bind with trade to find plan</color>\n<color:#999>Use plan to check if trade is due</color>
alt trade is due
China --> Alipay : Get subscription_id bind with the trade, initiate a debit request use subscription_id
Alipay --> China : Notify auto debit result with subscription_id/trade_no\n<color:#999>Use subscription_id/trade_no to find notify_url</color>
China --> Orange : Notify auto debit result to notify_url with trade_no/subscription_id/customer_id\n<color:#999>Bind member with trade_no/subscription_id/customer_id</color>
end
end
end
@enduml